// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgaBI6W4tadfdKF-94i7LJ_7s6E9l_S6s',
    appId: '1:665937901757:web:ee409424968b633c1bdfd4',
    messagingSenderId: '665937901757',
    projectId: 'women-safety-81e5e',
    authDomain: 'women-safety-81e5e.firebaseapp.com',
    storageBucket: 'women-safety-81e5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-okaiM2u-5PArY90L__KAdTRr-lm484',
    appId: '1:665937901757:android:4615f560f66414fb1bdfd4',
    messagingSenderId: '665937901757',
    projectId: 'women-safety-81e5e',
    storageBucket: 'women-safety-81e5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByJpLwzQ1nRmGJq0_IiM0mhYRiWEjZ24Y',
    appId: '1:665937901757:ios:8b526c4daeebf2ec1bdfd4',
    messagingSenderId: '665937901757',
    projectId: 'women-safety-81e5e',
    storageBucket: 'women-safety-81e5e.appspot.com',
    iosBundleId: 'com.example.safetyPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByJpLwzQ1nRmGJq0_IiM0mhYRiWEjZ24Y',
    appId: '1:665937901757:ios:8b526c4daeebf2ec1bdfd4',
    messagingSenderId: '665937901757',
    projectId: 'women-safety-81e5e',
    storageBucket: 'women-safety-81e5e.appspot.com',
    iosBundleId: 'com.example.safetyPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgaBI6W4tadfdKF-94i7LJ_7s6E9l_S6s',
    appId: '1:665937901757:web:aa85c4c427a4edc81bdfd4',
    messagingSenderId: '665937901757',
    projectId: 'women-safety-81e5e',
    authDomain: 'women-safety-81e5e.firebaseapp.com',
    storageBucket: 'women-safety-81e5e.appspot.com',
  );
}
